apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-event-api
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-event-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-event-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-event-api/metrics
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 2
    max: 4
  azure:
    application:
      enabled: true
      allowAllUsers: true
  ingresses:
    - "https://person.nav.no/tms-event-api"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 64Mi
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
        - application: modiapersonoversikt-api
          namespace: personoversikt
          cluster: prod-fss
        - application: modiapersonoversikt-api
          namespace: personoversikt
          cluster: prod-gcp
    outbound:
      rules:
        - application: tms-varsel-authority
  env:
    - name: VARSEL_AUTHORITY_CLIENT_ID
      value: prod-gcp.min-side.tms-varsel-authority

